previews:
  generation: automatic   # Creates a preview for every Pull Request

services:
  - type: web
    name: vite-app
    runtime: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
